#!/bin/bash

# sourcing centerIt
source "/etc/update-motd.d/functions/centerIt.sh"

printf "\n"
centerIt "53" "  ██████ ██▓███▄    █       ██▓   ▄▄▄      ███▄    █ "
centerIt "53" "▒██    ▒▓██▒██ ▀█   █      ▓██▒  ▒████▄    ██ ▀█   █ "
centerIt "53" "░ ▓██▄  ▒██▓██  ▀█ ██▒     ▒██░  ▒██  ▀█▄ ▓██  ▀█ ██▒"
centerIt "53" "  ▒   ██░██▓██▒  ▐▌██▒     ▒██░  ░██▄▄▄▄██▓██▒  ▐▌██▒"
centerIt "53" "  ▒   ██░██▓██▒  ▐▌██▒     ▒██░  ░██▄▄▄▄██▓██▒  ▐▌██▒"
centerIt "53" "▒██████▒░██▒██░   ▓██░ ██▓ ░██████▓█   ▓██▒██░   ▓██░"
centerIt "53" "▒ ▒▓▒ ▒ ░▓ ░ ▒░   ▒ ▒  ▒▓▒ ░ ▒░▓  ▒▒   ▓▒█░ ▒░   ▒ ▒ "
centerIt "53" "░ ░▒  ░ ░▒ ░ ░░   ░ ▒░ ░▒  ░ ░ ▒  ░▒   ▒▒ ░ ░░   ░ ▒░"
centerIt "53" "░  ░  ░  ▒ ░  ░   ░ ░  ░     ░ ░   ░   ▒     ░   ░ ░ "
centerIt "53" "      ░  ░          ░   ░      ░  ░    ░  ░        ░ "
centerIt "53" "                        ░                            "
printf "\n"